### ISSUE TITLE
what this repo is about?

### ISSUE THREAD

**Issue by AshishGuptaNGupta** [mmontz/Cracking-the-Coding-Inteview-6th-Edition#1]
Hi Ashley, 

I am preparing for interviews too. I like to know what this repo is about.I know what CTCI is, as it very popular book

**Comment by mmontz** [comment]
Hey,

Thanks for reaching out. I made that repo 2 years ago when I was working on
CTCI problems. The file names are the chapter number followed by the
problem number i.e. 4.3 means question 3 of chapter 4.

Good luck with your interview prep!
Ashley

**Comment by AshishGuptaNGupta** [comment]
Thanks a lot this info👍  you done with your interview endeavour or still working towards it?

**Comment by mmontz** [comment]
You're welcome! Yes I'm almost done. Hope yours go great as well! Just out
of curiosity, may I ask how you found my Github repo?

Regards,
Ashley

**Comment by AshishGuptaNGupta** [comment]
I saw your post on leetcode.  So there i thought to check your github.

**Comment by mmontz** [comment]
gotcha! happy leetcoding then! and good luck with your job search!

**Comment by AshishGuptaNGupta** [comment]
I m from India. And here it feels, even after all practise and training, finding a good job is difficult. Forget about something big as faang. Anyways thanks for well wishes✌️

**Comment by mmontz** [comment]
Yeah I understand. I know how frustrating job hunting can be. But keep
practicing and being patient. I'm sure soon you'll get a great job. Best
wishes.
